services:
  app.menu_builder:
    class: App\Menu\MenuBuilder
    arguments: ["@knp_menu.factory", "@security.helper"]
    tags:
      - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu
