# Basic LAMP stack

version: "2.1"

services:
  # Web
  apache:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: apache
    depends_on:
      - cli
  # Web
  api:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: apache
    hostname: api
    volumes:
      - api_root:/var/www:ro,nocopy,cached  # Project root volume (read-only)
    labels:
      - io.docksal.virtual-host=api.${VIRTUAL_HOST}
    environment:
      - APACHE_DOCUMENTROOT=/var/www

  # DB
  db:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mysql

  # CLI
  cli:
    image: ${COMPOSE_PROJECT_NAME_SAFE}_cli
    build:
      context: services/cli
      args:
        - CLI_IMAGE=${CLI_IMAGE:-docksal/cli:2.13-php7.4}
    environment:
      - XDEBUG_CONFIG=${XDEBUG_CONFIG:-discover_client_host=1}

  # Mail
  mail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mail  # Adminer
  adminer:
    hostname: adminer
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=db # db is the default database container
      - ADMINER_PLUGINS=tables-filter tinymce # To load Adminer plugins
      - ADMINER_DESIGN=price # To use a bundled Adminer design
    labels:
      - io.docksal.virtual-host=adminer.${VIRTUAL_HOST}

volumes:
  api_root:  # Project root volume (bind mount)
    driver: local
    driver_opts:
      type: none
      device: ${PROJECT_ROOT}/api_example/react/build
      o: bind