twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        app_locales: '%app.supported_locales%'
when@test:
    twig:
        strict_variables: true
